server:
  port: 8080

spring:
  application:
    name: spring-ai-rag


  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        options:
          model: llama3

      embedding:
        options:
          model: nomic-embed-text


    vectorstore:
     pgvector:
       initialize-schema: true